echo "<html lang=\"en-us\">\n";
echo "\n";
echo "<head>\n";
echo "    <meta charset=\"utf-8\" />\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, user-scalable=no\" />\n";
echo "    <meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\" />\n";
echo "    <meta name=\"theme-color\" content=\"#\" />\n";
echo "    <title>Invest In Innovation Forum</title>\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Fira+Sans:200,300i,400,600,800\" rel=\"stylesheet\" />\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap\" rel=\"stylesheet\" />\n";
echo "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n";
echo "    <link href=\"css/style.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"css/shame.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"schedule.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"Fontawesome/js/fontawesome.min.js\" rel=\"stylesheet\" />\n";
echo "    <link href=\"Fontawesome/css/all.min.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"Fontawesome/css/brands.min.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"lib/venobox/venobox.css\" rel=\"stylesheet\" />\n";
echo "    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\" />\n";
echo "    <title>Invest in Innovation Forum</title>\n";
echo "    <meta name=\"robots\" content=\"max-image-preview:large\" />\n";
echo "    <meta name=\"description\"\n";
echo "        content=\"Innovation Forum is proud to present Invest In Innovation, a high caliber, two-day conference displaying the future of the healthcare industry in the next big Innovation Hub, Barcelona, Spain. Get an early-bird ticket now!\" />\n";
echo "    <meta name=\"robots\" content=\"max-snippet:-1, max-image-preview:large, max-video-preview:-1\" />\n";
echo "    <meta property=\"og:locale\" content=\"en_GB\" />\n";
echo "    <meta property=\"og:type\" content=\"website\" />\n";
echo "    <meta property=\"og:title\" content=\"Invest in Innovation Forum - Get Your Tickets Now !!\" />\n";
echo "    <meta property=\"og:description\"\n";
echo "        content=\"Innovation Forum is proud to present Invest In Innovation, a high caliber, two-day conference displaying the future of the healthcare industry in the next big Innovation Hub, Barcelona, Spain. Get an early-bird ticket now!\" />\n";
echo "    <!-- <meta property=\"og:url\" content=\"\" />  -->\n";
echo "    <meta property=\"og:site_name\" content=\"Invest In Innovation Conference\" />\n";
echo "    <meta name=\"twitter:card\" content=\"summary_large_image\" />\n";
echo "    <meta name=\"twitter:description\"\n";
echo "        content=\"Innovation Forum is proud to present Invest In Innovation, a high caliber, two-day conference displaying the future of the healthcare industry in the next big Innovation Hub, Barcelona, Spain. Get an early-bird ticket now!\" />\n";
echo "    <meta name=\"twitter:title\" content=\"Invest in Innovation Forum - Get Your Tickets Now !!\" />\n";
echo "    <meta name=\"twitter:site\" content=\"@Innovation_F\" />\n";
echo "    <meta name=\"twitter:creator\" content=\"@Innovation_F\" />\n";
echo "    <meta name=\"msvalidate.01\" content=\"D6557E4B5E5DD53DD208AFF318657C1C\" />\n";
echo "    <meta name=\"google-site-verification\" content=\"PuX6EXnyDmk45ChRIzCTh4MF5u4_9XWu0lNHl1YGXoU\" />\n";
echo "    <meta name=\"yandex-verification\" content=\"078df958e13ba313\" />\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <script type=\"text/javascript\">\n";
echo "        // _linkedin_partner_id = \"956956\";\n";
echo "\n";
echo "        window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];\n";
echo "\n";
echo "        window._linkedin_data_partner_ids.push(_linkedin_partner_id);\n";
echo "    </script>\n";
echo "    <script type=\"text/javascript\">\n";
echo "        (function () {\n";
echo "            var s = document.getElementsByTagName(\"script\")[0];\n";
echo "\n";
echo "            var b = document.createElement(\"script\");\n";
echo "\n";
echo "            b.type = \"text/javascript\";\n";
echo "            b.async = true;\n";
echo "\n";
echo "            b.src = \"https://snap.licdn.com/li.lms-analytics/insight.min.js\";\n";
echo "\n";
echo "            s.parentNode.insertBefore(b, s);\n";
echo "        })();\n";
echo "    </script>\n";
echo "    <nav class=\"main-navbar navbar navbar-expand-xl fixed-top justify-content-between navbar-dark\">\n";
echo "        <div class=\"container\">\n";
echo "            <div class=\"navbar-brand\"> <a href=\"#index\"> <img class=\"logo-dark\" src=\"images/logo_innoforum.svg\"\n";
echo "                        alt=\"Innovation Forum\" width=\"160\" height=\"60\"> <img class=\"logo-light\"\n";
echo "                        src=\"images/logo_innoforum.svg\" alt=\"Innovation Forum\" width=\"160\" height=\"60\"> </a></div>\n";
echo "            <button class=\"navbar-toggler collapsed\" type=\"button\" data-toggle=\"collapse\"\n";
echo "                data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n";
echo "                aria-label=\"Toggle navigation\"> <span class=\"icon-bar\"></span> </button>\n";
echo "            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n";
echo "                <ul class=\"navbar-nav ml-auto\">\n";
echo "                    </li>\n";
echo "                    <li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.php\">Home</a></li>\n";
echo "                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"startup.php\">Start-Ups</a></li>\n";
echo "                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"investors.php\">Investors</a></li>\n";
echo "                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"partners.html\">Partners</a></li>\n";
echo "                    <li class=\"nav-item\"><a class=\"btn btn-primary\" href=\"https://innovationforum.ticketspice.com/invest-in-innovation\" target=\"_blank\" rel=\"noopener noreferrer\" role=\"button\">Buy Tickets</a></li>\n";
echo "                </ul>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </nav>\n";
echo "    <script>\n";
echo "        $(document).ready(function () {\n";
echo "            $(\".main-navbar .navbar-toggler\").on(\"click\", function () {\n";
echo "                $('.main-navbar').toggleClass('opened');\n";
echo "            });\n";
echo "\n";
echo "            if ($('body').hasClass('faq-article')) {\n";
echo "                $('.main-navbar	').addClass('navbar-light bg-light').removeClass('navbar-dark');\n";
echo "            } else {\n";
echo "                $(\".main-navbar .navbar-toggler\").on(\"click\", function () {\n";
echo "                    if ($(window).scrollTop() < 1 && $('.navbar-collapse.collapse').hasClass('show')) {\n";
echo "                        $('.main-navbar').removeClass('navbar-light bg-light').addClass('navbar-dark');\n";
echo "                    } else {\n";
echo "                        $('.main-navbar	').addClass('navbar-light bg-light').removeClass('navbar-dark');\n";
echo "                    }\n";
echo "                });\n";
echo "                $(window).on('scroll', function () {\n";
echo "                    if ($(window).scrollTop() >= 1) {\n";
echo "                        $('.main-navbar').addClass('navbar-light bg-light').removeClass('navbar-dark');\n";
echo "                    } else if ($(window).scrollTop() < 1 && $('.navbar-collapse.collapse').hasClass(\n";
echo "                            'show')) {\n";
echo "                        $('.main-navbar').addClass('navbar-light bg-light').removeClass('navbar-dark');\n";
echo "                    } else {\n";
echo "                        $('.main-navbar').removeClass('navbar-light bg-light').addClass('navbar-dark');\n";
echo "                    }\n";
echo "                });\n";
echo "            }\n";
echo "\n";
echo "            $(document).keyup(function (e) {\n";
echo "                if (e.keyCode == 27) {\n";
echo "                    if ($('.navbar-collapse.collapse').hasClass('show')) {\n";
echo "                        $(\".navbar-toggler\").click();\n";
echo "                    }\n";
echo "                }\n";
echo "            });\n";
echo "        });\n";
echo "    </script>\n";
echo "    <main id=\"index\">\n";
echo "        <header class=\"default home-header video-header\">\n";
echo "            <div class=\"home-header-bg\"\n";
echo "                style=\"background-image:url('https://www.horizons.health/wp-content/themes/hh-moka/media/home-header-bg.jpg')\">\n";
echo "            </div>\n";
echo "            <div class=\"video-container\">\n";
echo "                <video webkit-playsinline=\"\" autoplay=\"\" loop=\"\" muted=\"\">\n";
echo "                    <source src=\"videos/mainpage.mp4\">\n";
echo "                </video>\n";
echo "            </div>\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"ini-logo\"> <img src=\"images/ini_logo.svg\" alt=\"Invest In Innovation Logo\" width=\"330\"\n";
echo "                        height=\"122\"></div>\n";
echo "                <img src=\"images/Explore.svg\" alt=\"Explore New Investments\" width=\"654\" height=\"177\" style=\"\n";
echo "                            margin-bottom: 75px;\">\n";
echo "                <section class=\"explore\" style=\"margin-bottom: 75px;\">\n";
echo "                    <p style=\" width: 597px; height: 107px;\">Join the Innovators Shaping the Future of Health in Our\n";
echo "                        Global 2-Day Virtual Conference</p>\n";
echo "                </section>\n";
echo "                <div class=\"d-flex justify-content-center\">\n";
echo "                    <span class=\"buy-ticket-btn\">\n";
echo "                        <a href=\"https://innovationforum.ticketspice.com/invest-in-innovation\" target=\"_blank\" rel=\"noopener noreferrer\"><button class=\"btn btn-primary btn-lg active\">Buy Tickets</button></a>\n";
echo "                    </span>\n";
echo "                </div>\n";
echo "        </header>\n";
echo "        <section class=\"section-about\" style=\" margin-top: 50px; margin-bottom: 50px;\">\n";
echo "            <div class=\"container-fluid\">\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-lg-4 img-what-is\">\n";
echo "                        <img src=\"images/what-is.svg\" alt=\"What Is Innovation Forum\" width=\"374\" height=\"117.6\">\n";
echo "                    </div>\n";
echo "                    <?php echo '<a href=\"startup.php\">startups</a>';?>\n";
echo "                    <div class=\"col-lg-8\" style=\"\n";
echo "                        padding-left: 80px;\n";
echo "                        padding-right: 0px;\n";
echo "                    \">\n";
echo "                        <p class=\"whatis-if\">Invest in Innovation brings together leading investors and founders from\n";
echo "                            around the health and technology space to set the agenda for the next stage in healthcare\n";
echo "                            innovation.\n";
echo "                            Meet the founders transforming health in the digital, biotech, pharma, AI and medtech space\n";
echo "                            and the investors and policy makers setting the stage to make them happen.<br>\n";
echo "\n";
echo "                            <br>Over the past 8 years, the global Innovation Forum network has featured the most vibrant\n";
echo "                            health-tech ecosystems in Europe and as in proud to highlight Barcelona as one of the\n";
echo "                            fastest growing European ecosystems in 2021 in this 2 day virtual conference.\n";
echo "                        </p>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <section>\n";
echo "            <img src=\"images/border.svg\" alt=\"border\" width=\"2000\" height=\"66\">\n";
echo "        </section>\n";
echo "        <section class=\"description_ini\">\n";
echo "            <div class=\"container-fluid\">\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-lg-6\">\n";
echo "                        <div class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\n";
echo "                            <div class=\"panel panel-default\">\n";
echo "                                <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\n";
echo "                                    <h4 class=\"panel-title\">\n";
echo "                                        <a role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\"\n";
echo "                                            href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\"\n";
echo "                                            class=\"\">\n";
echo "                                            Why Invest in Innovation ?\n";
echo "                                        </a>\n";
echo "                                    </h4>\n";
echo "                                </div>\n";
echo "                                <div id=\"collapseOne\" class=\"panel-collapse in collapse show\" role=\"tabpanel\"\n";
echo "                                    aria-labelledby=\"headingOne\" style=\"\">\n";
echo "                                    <div class=\"panel-body\">\n";
echo "                                        <p>The past year has seen the largest globally coordinated efforts of\n";
echo "                                            scientists, policy makers and investment in history to tackle an\n";
echo "                                            unprecedented challenge. As we emerge on the other side, the question is:\n";
echo "                                            <b>where next?</b><br>\n";
echo "\n";
echo "                                            <br>How do we take this momentum and combine it the maturation of gene\n";
echo "                                            technologies, AI, cell therapies and advanced devices to catapult the next\n";
echo "                                            generation of healthcare start-ups?<br>\n";
echo "\n";
echo "                                            <br>Join the leading founders, investors and decision makers to scope out\n";
echo "                                            the next major opportunities and shape the next stage of health-related\n";
echo "                                            start-ups.</p>\n";
echo "                                    </div>\n";
echo "                                    <div class=\"panel panel-default\">\n";
echo "                                        <div class=\"panel-heading\" role=\"tab\" id=\"headingTwo\">\n";
echo "                                            <h4 class=\"panel-title\">\n";
echo "                                                <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\"\n";
echo "                                                    data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\"\n";
echo "                                                    aria-controls=\"collapseTwo\">\n";
echo "                                                    Why Barcelona ?\n";
echo "                                                </a>\n";
echo "                                            </h4>\n";
echo "                                        </div>\n";
echo "                                        <div id=\"collapseOne\" class=\"panel-collapse in collapse show\" role=\"tabpanel\"\n";
echo "                                            aria-labelledby=\"headingOne\" style=\"\">\n";
echo "                                            <div class=\"panel-body\">\n";
echo "                                                <div class=\"panel-body\">\n";
echo "                                                    <p>With the Catalonia ‘Bioregion’ seeing one company a week being\n";
echo "                                                        founded it is\n";
echo "                                                        clear that this ecosystem is a growing opportunity for\n";
echo "                                                        healthcare\n";
echo "                                                        investment. In recent years, it has developed to a stage of\n";
echo "                                                        maturity with\n";
echo "                                                        key infrastructure of entrepreneurial support and investment\n";
echo "                                                        capital\n";
echo "                                                        doubling over the last 2 years and a x5 increase in\n";
echo "                                                        international\n";
echo "                                                        investment. With 5+ years in the region, the Innovation Forum is\n";
echo "                                                        keen to\n";
echo "                                                        showcase this ecosystem which has positioned its health\n";
echo "                                                        innovation to the\n";
echo "                                                        top of its agenda.</p>\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-6\">\n";
echo "                        <img src=\"Invest In Innovation /1916-health-horizons-2019-306.png\"\n";
echo "                            alt=\"Invest In Innovation Logo\" width=\"572\" height=\"572\">\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <section class=\"testimonials\">\n";
echo "            <div id=\"carouselTestimonials\" class=\"carousel slide carousel-fade\" data-ride=\"carousel\" data-pause=\"true\">\n";
echo "                <div class=\"carousel-inner\">\n";
echo "                    <div class=\"carousel-item text-right active\">\n";
echo "                        <div class=\"carousel-item-content\">\n";
echo "                            <div class=\"testimonial-image\">\n";
echo "                                <img width=\"240\" height=\"361\" src=\"images/castlett.svg\"\n";
echo "                                    class=\"attachment-speakerlist size-speakerlist\"\n";
echo "                                    alt=\"Invest In Innovation - Richard Castellet\" loading=\"lazy\"\n";
echo "                                    srcset=\"images/castlett.svg 240w, images/castlett.svg 150w, images/castlett.svg 300w, images/castlett.svg 768w, images/castlett.svg 900w\"\n";
echo "                                    sizes=\"(max-width: 238px) 100vw, 238px\" />\n";
echo "                            </div>\n";
echo "                            <div class=\"container text-left\">\n";
echo "                                <div class=\"row justify-content-right justify-content-md-right\">\n";
echo "                                    <div class=\"col-11 col-md-10 offset-lg-1 col-lg-8\">\n";
echo "                                        <blockquote>“The Barcelona ecosystem has everything to consolidate itself as a\n";
echo "                                            world reference hub in #healthtech. We are entering a new phase of the\n";
echo "                                            ecosystem, of creation and growth, to the phase of specialization in sectors\n";
echo "                                            where there is excellence and international competitiveness. The Catalan\n";
echo "                                            health ecosystem, in the middle of the digital transformation process, at\n";
echo "                                            the crossroads of exponential technological disruption and new business\n";
echo "                                            models, is ready for this new phase of international consolidation”\n";
echo "                                        </blockquote>\n";
echo "                                        <div class=\"testimonial-author\">\n";
echo "                                            <p class=\"author-name\">Richard Castellet</p>\n";
echo "                                            <p class=\"author-position\">Digital Transformation Officer at Gebro Pharma\n";
echo "                                            </p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"carousel-item text-right \">\n";
echo "                        <div class=\"carousel-item-content\">\n";
echo "                            <div class=\"testimonial-image\">\n";
echo "                                <img width=\"240\" height=\"361\" src=\"images/Dan.jpeg\"\n";
echo "                                    class=\"attachment-speakerlist size-speakerlist\"\n";
echo "                                    alt=\"Health Horizons Conference - Hermann Hauser\" loading=\"lazy\"\n";
echo "                                    srcset=\"images/Dan.jpeg 240w, images/Dan.jpeg 150w, images/Dan.jpeg 300w, images/Dan.jpeg 900w\"\n";
echo "                                    sizes=\"(max-width: 238px) 100vw, 238px\" />\n";
echo "                            </div>\n";
echo "                            <div class=\"container text-left\">\n";
echo "                                <div class=\"row justify-content-center justify-content-md-center\">\n";
echo "                                    <div class=\"col-11 col-md-10 offset-lg-1 col-lg-8\">\n";
echo "                                        <blockquote>“During the recent decade, Barcelona has grown to be an acknowledged\n";
echo "                                            health innovation hub. Its thriving start-up ecosystem, together with\n";
echo "                                            world-leading organisations make open numerous possibilities for\n";
echo "                                            collaborations and investments.\n";
echo "                                            I believe an event like Invest in Innovation is necessary in order to build\n";
echo "                                            long standing partnerships and showcase how much Barcelona can offer to the\n";
echo "                                            world.”\n";
echo "                                        </blockquote>\n";
echo "                                        <div class=\"testimonial-author\">\n";
echo "                                            <p class=\"author-name\">Daniel Moreno Martínez, PhD, FHEA</p>\n";
echo "                                            <p class=\"author-position\">Head of the Innovation Programme</p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"carousel-item text-right \">\n";
echo "                        <div class=\"carousel-item-content\">\n";
echo "                            <div class=\"testimonial-image\">\n";
echo "                                <img width=\"240\" height=\"361\" src=\"images/andy-richards.jpg\"\n";
echo "                                    class=\"attachment-speakerlist size-speakerlist\"\n";
echo "                                    alt=\"Health Horizons Conference - Hermann Hauser\" loading=\"lazy\"\n";
echo "                                    srcset=\"images/andy-richards.jpg 240w, images/andy-richards.jpg 150w, images/andy-richards.jpg 300w, images/andy-richards.jpg 900w\"\n";
echo "                                    sizes=\"(max-width: 238px) 100vw, 238px\" />\n";
echo "                            </div>\n";
echo "                            <div class=\"container text-left\">\n";
echo "                                <div class=\"row justify-content-center justify-content-md-center\">\n";
echo "                                    <div class=\"col-11 col-md-10 offset-lg-1 col-lg-8\">\n";
echo "                                        <blockquote>““Exciting, really dynamic atmosphere and I look forward to be\n";
echo "                                            involved in these events in the future”\n";
echo "                                        </blockquote>\n";
echo "                                        <div class=\"testimonial-author\">\n";
echo "                                            <p class=\"author-name\">Dr. Andy Richards</p>\n";
echo "                                            <p class=\"author-position\"> Chairman of 4 biotech companies and founder of\n";
echo "                                                Cambridge Angels</p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"carousel-item text-right \">\n";
echo "                        <div class=\"carousel-item-content\">\n";
echo "                            <div class=\"testimonial-image\">\n";
echo "                                <img width=\"240\" height=\"361\" src=\"images/Dr-Hermann-Hauser.jpg\"\n";
echo "                                    class=\"attachment-speakerlist size-speakerlist\"\n";
echo "                                    alt=\"Health Horizons Conference - Hermann Hauser\" loading=\"lazy\"\n";
echo "                                    srcset=\"images/Dr-Hermann-Hauser.jpg 240w, images/Dr-Hermann-Hauser.jpg 150w, images/Dr-Hermann-Hauser.jpg 300w, images/Dr-Hermann-Hauser.jpg 900w\"\n";
echo "                                    sizes=\"(max-width: 238px) 100vw, 238px\" />\n";
echo "                            </div>\n";
echo "                            <div class=\"container text-left\">\n";
echo "                                <div class=\"row justify-content-center justify-content-md-center\">\n";
echo "                                    <div class=\"col-11 col-md-10 offset-lg-1 col-lg-8\">\n";
echo "                                        <blockquote>“I was blown away! I am so impressed that there are so many good\n";
echo "                                            companies now”\n";
echo "                                        </blockquote>\n";
echo "                                        <div class=\"testimonial-author\">\n";
echo "                                            <p class=\"author-name\">Dr. Hermann Hauser</p>\n";
echo "                                            <p class=\"author-position\">Founder & Director at Amadeus Capital Partners\n";
echo "                                            </p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"arrows\">\n";
echo "                        <div class=\"container\">\n";
echo "                            <div class=\"row justify-content-center justify-content-md-center\">\n";
echo "                                <div class=\"col-11 col-md-10 offset-lg-1 col-lg-8\">\n";
echo "                                    <a class=\"carousel-control-prev\" href=\"#carouselTestimonials\" role=\"button\"\n";
echo "                                        data-slide=\"prev\">\n";
echo "                                        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n";
echo "                                        <span class=\"sr-only\">Previous</span>\n";
echo "                                    </a>\n";
echo "                                    <a class=\"carousel-control-next\" href=\"#carouselTestimonials\" role=\"button\"\n";
echo "                                        data-slide=\"next\">\n";
echo "                                        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n";
echo "                                        <span class=\"sr-only\">Next</span>\n";
echo "                                    </a>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "        </section>\n";
echo "        <section id=\"schedule\" class=\"section-with-bg\">\n";
echo "            <div class=\"container-fluid\">\n";
echo "                <div class=\"section-header\">\n";
echo "                    <img src=\"images/event_schedule.svg\" alt=\"Invest In Innovation Logo\" width=\"158\" height=\"46\">\n";
echo "                </div>\n";
echo "                <!-- <div>\n";
echo "                    <ul class=\"nav nav-tabs\" role=\"tablist\">\n";
echo "                        <li class=\"nav-item\" style=\"\n";
echo "                    padding-right: 100px;\n";
echo "                    margin-right: 150px;\n";
echo "                    \">\n";
echo "                            <a class=\"nav-link\" style=\"\n";
echo "                        padding-right: 100px;\" data-toggle=\"tab\"><span class=\"day\">Day 1 :</span><br>9 November\n";
echo "                                2021</a>\n";
echo "                        </li>\n";
echo "                        \n";
echo "                    </ul>\n";
echo "                </div> -->\n";
echo "                <div class=\"tab-content row justify-content-center\">\n";
echo "                    <div class=\"container\">\n";
echo "                        <div class=\"row\">\n";
echo "                            <div class=\"col-md-6\" style=\"\n";
echo "                            padding-left: 100px\">\n";
echo "                                <ul class=\"nav nav-tabs\" role=\"tablist\">\n";
echo "                                    <li class=\"nav-item\" style=\"\n";
echo "                            padding-right: 100px;\n";
echo "                            margin-right: 150px;\n";
echo "                            \">\n";
echo "                                    <li class=\"nav-item\">\n";
echo "                                        <a class=\"nav-link\" style=\"\n";
echo "                                padding-left: 100px;\" data-toggle=\"tab\"><span class=\"day\">Day 1 :</span><br>09 November\n";
echo "                                            2021</a>\n";
echo "                                    </li>\n";
echo "                                </ul>\n";
echo "                                <h4 class=\"session\">Session 1</h4>\n";
echo "                                <br>\n";
echo "                                <h2 class=\"session-title\">Barcelona as an Innovation Hub</h2>\n";
echo "                                <br>\n";
echo "                                <p class=\"session-info\">Hear from the leaders who have shaped Barcelona into a major\n";
echo "                                    European innovation hub. From high-level policy makers to successful\n";
echo "                                    entrepreneurs, hear the stories of how this ecosystem has planted its roots and\n";
echo "                                    now rapidly growing and flourishing.</p>\n";
echo "                                <br>\n";
echo "                                <h4 class=\"session\">Break</h4>\n";
echo "                                <br>\n";
echo "                                <h3 class=\"session-title\">Break and Networking</h3>\n";
echo "                                <br>\n";
echo "                                <h4 class=\"session\">Session 2</h4>\n";
echo "                                <br>\n";
echo "                                <h2 class=\"session-title\">Investment in Health-tech and Life Science</h2>\n";
echo "                                <br>\n";
echo "                                <p class=\"session-info\">We explore the current investment vehicles and opportunities\n";
echo "                                    both in the Barcelona region and more broadly in the European landscape in the\n";
echo "                                    health tech, bio tech and med tech sectors. Discover key considerations in\n";
echo "                                    investing in different ecosystems, the developing regulations being introduced\n";
echo "                                    to address new challenges, and how these may affect your firm/company. </p>\n";
echo "                            </div>\n";
echo "                            <div class=\"col-md-6\" style=\"\n";
echo "                                padding-left: 100px\">\n";
echo "                                <ul class=\"nav nav-tabs\" role=\"tablist\">\n";
echo "                                    <li class=\"nav-item\" style=\"\n";
echo "                                padding-right: 100px;\n";
echo "                                margin-right: 150px;\n";
echo "                                \">\n";
echo "                                    <li class=\"nav-item\">\n";
echo "                                        <a class=\"nav-link\" style=\"\n";
echo "                                    padding-left: 100px;\" data-toggle=\"tab\"><span class=\"day\">Day 2 :</span><br>10\n";
echo "                                            November\n";
echo "                                            2021</a>\n";
echo "                                    </li>\n";
echo "                                </ul>\n";
echo "                                <h4 class=\"session\">Session 3</h4>\n";
echo "                                <br>\n";
echo "                                <h2 class=\"session-title\">Emerging Trends in Health</h2>\n";
echo "                                <br>\n";
echo "                                <br>\n";
echo "                                <p class=\"session-info\">We gather key opinion leaders in both academia, successful\n";
echo "                                    start-ups and leading companies to discuss the vast emergence new opportunities\n";
echo "                                    across biotech, health tech and med tech fueled by innovative research and\n";
echo "                                    visionary entrepreneurs.</p>\n";
echo "                                <br>\n";
echo "                                <h4 class=\"session\">Break</h4>\n";
echo "                                <br>\n";
echo "                                <h3 class=\"session-title\">Break and Networking</h3>\n";
echo "                                <br>\n";
echo "                                <h4 class=\"session\">Session 4</h4>\n";
echo "                                <br>\n";
echo "                                <h2 class=\"session-title\">Start-up Pitching</h2>\n";
echo "                                <br>\n";
echo "                                <br>\n";
echo "                                <p class=\"session-info\">Hear from the most talented and passionate founders aspiring\n";
echo "                                    to transform the industry with their groundbreaking technologies. From seed to\n";
echo "                                    Series A, we’ll present a range of opportunities culminating in our IMAGINE IF!\n";
echo "                                    accelerator final where our global top 15 pitch to win non-dilutive funding\n";
echo "                                    having been whittled down from almost 200 global applicants through multiple\n";
echo "                                    stages of evaluation.</p>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <script src=\"javascript/slick.js\"></script>\n";
echo "        <section>\n";
echo "            <img src=\"images/border.svg\" alt=\"border\" width=\"2000\" height=\"66\">\n";
echo "        </section>\n";
echo "        <section id=\"advisors\" class=\"section-with-bg\">\n";
echo "            <div class=\"container-fluid\">\n";
echo "                <div class=\"section-header\">\n";
echo "                    <div class=\"venue\">\n";
echo "                        <img src=\"images/advisors.svg\" alt=\"Invest In Innovation Logo\" width=\"158\" height=\"46\">\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"row\" style=\"margin-left: 60px;\">\n";
echo "                <div class=\"col-md-3\">\n";
echo "                    <div class=\"thumbnail\">\n";
echo "                        <img src=\"images/Daniel-Oliver-Capital-Cell.jpg\" alt=\"Daniel Oliver\"\n";
echo "                            style=\"width:50%;margin-left: 100px;margin-top: 25px;\">\n";
echo "                        <div class=\"advisor-caption\" style=\"\n";
echo "                      padding-top: 50px\">\n";
echo "                            <h3>Daniel Oliver</h3>\n";
echo "                            <h6>CEO, Capital Cell</h6>\n";
echo "                        </div>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-md-3 \">\n";
echo "                    <div class=\"thumbnail\">\n";
echo "                        <img src=\"images/Daniel+Moreno+Martinez.jpg\" alt=\"Dr. Daniel Moreno Martinez\"\n";
echo "                            class=\"d-flex justify-content-center\"\n";
echo "                            style=\"width:50%;margin-left: 100px;margin-top: 25px;\">\n";
echo "                        <div class=\"advisor-caption\" style=\"\n";
echo "                      padding-top: 50px\">\n";
echo "                            <h3>Dr. Daniel Moreno</h3>\n";
echo "                            <h6>Head of the innovation programme, Hospital Germans Trias i Pujol </h6>\n";
echo "                        </div>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-md-3\">\n";
echo "                    <div class=\"thumbnail\">\n";
echo "                        <img src=\"images/ignasi heras.jpg\" alt=\"Ignasi Heras\"\n";
echo "                            style=\"width:50%;margin-left: 100px;margin-top: 25px;\">\n";
echo "                        <div class=\"advisor-caption\" style=\"\n";
echo "                      padding-top: 50px\">\n";
echo "                            <h3>Ignasi Heras</h3>\n";
echo "                            <h6>VC investor</h6>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            </div>\n";
echo "            <br>\n";
echo "            <br>\n";
echo "            <br>\n";
echo "            <br>\n";
echo "        </section>\n";
echo "        <section>\n";
echo "            <img src=\"images/border.svg\" alt=\"border\" width=\"2000\" height=\"66\">\n";
echo "        </section>\n";
echo "        <section class=\"section-default mailing-list\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"row justify-content-center\">\n";
echo "                    <div class=\"col-md-8 col-lg-10\">\n";
echo "                        <div class=\"row\">\n";
echo "                            <div class=\"col-lg-6 mailing-list-description\">\n";
echo "                                <h3 id=\"contactus\" class=\"section-title\">JOIN OUR MAILING LIST</h3>\n";
echo "                                <p>Stay up to date with news on Invest In Innovation, including an updated schedule and\n";
echo "                                    speaker\n";
echo "                                    announcements</p>\n";
echo "                            </div>\n";
echo "                            <div class=\"col-lg-6 pt-2\">\n";
echo "                                <div class=\"form-group\">\n";
echo "                                    <input id=\"subscribe_email\" class=\"form-control\" type=\"text\" placeholder=\"Email\">\n";
echo "                                    <div class=\"invalid-feedback\"> Please complete your email.</div>\n";
echo "                                </div>\n";
echo "                                <div class=\"form-group\">\n";
echo "                                    <input id=\"subscribe_company\" class=\"form-control\" type=\"text\"\n";
echo "                                        placeholder=\"Company name\">\n";
echo "                                    <div class=\"invalid-feedback\"> Please complete your company name.</div>\n";
echo "                                </div>\n";
echo "                                <div class=\"form-group\">\n";
echo "                                    <input id=\"subscribe_job\" class=\"form-control\" type=\"text\" placeholder=\"Job title\">\n";
echo "                                    <div class=\"invalid-feedback\"> Please complete your Job title.</div>\n";
echo "                                </div>\n";
echo "                                <div class=\"text-right\">\n";
echo "                                    <button id=\"subscribe_button\" class=\"btn btn-outline-primary\" href=\"\">Sign me\n";
echo "                                        up</button>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div id=\"subscribe_ok\" class=\"valid-feedback\"> Thanks!</div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <section>\n";
echo "            <footer class=\"site-footer\">\n";
echo "                <div class=\"container\">\n";
echo "                    <div class=\"row\" style=\"\n";
echo "                    margin-left: 35px;\n";
echo "                \">\n";
echo "                        <div class=\"col-xs-6 col-md-3\">\n";
echo "                            <!-- Partners -->\n";
echo "                        </div>\n";
echo "                        <hr>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"container\">\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"ini-footer\">\n";
echo "                            <div class=\"col-md-12\">\n";
echo "                                <img src=\"images/ini-logo_blk.svg\" alt=\"Invest in Innovation Logo\">\n";
echo "                                <div class=\"container\">\n";
echo "                                    <div class=\"col-md-6\"></div>\n";
echo "                                    <div class=\"row\">\n";
echo "                                        <div>\n";
echo "                                            <p class=\"copyright-text\">Copyright © 2021 All Rights Reserved by\n";
echo "                                                Innovation Forum.\n";
echo "                                            </p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "\n";
echo "                            <div class=\"col-md-6\">\n";
echo "                                <ul class=\"social-icons\">\n";
echo "                                    <li><a class=\"twitter\" href=\"https://twitter.com/Innovation_F\"><i\n";
echo "                                                class=\"fa fa-twitter\"></i></a></li>\n";
echo "                                    <li><a class=\"dribbble\" href=\"https://www.instagram.com/innovation_forum/\"><i\n";
echo "                                                class=\"fa fa-instagram\"></i></a></li>\n";
echo "                                    <li><a class=\"linkedin\" href=\"https://www.linkedin.com/company/innovation-forum\"><i\n";
echo "                                                class=\"fa fa-linkedin\"></i></a></li>\n";
echo "                                </ul>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                </div>\n";
echo "\n";
echo "            </footer>\n";
echo "        </section>\n";
echo "\n";
echo "\n";
echo "        </script>\n";
echo "        <script type=\"text/javascript\" src=\"javascript/bootstrap.min.js\"></script>\n";
echo "        <script src=\"javascript/popper.js\"></script>\n";
echo "        <script type=\"text/javascript\"></script>\n";
echo "        <script src=\"Fontawesome/js/v4-shims.min.js\"></script>\n";
echo "        <script src=\"Fontawesome/js/all.min.js\"></script>\n";
echo "        <script src=\"Fontawesome/js/brands.min.js\"></script>\n";
echo "        <script src=\"Fontawesome/js/conflict-detection.min.js\"></script>\n";
echo "        <script src=\"Fontawesome/js/fontawesome.min.js\"></script>\n";
echo "        <script src=\"lib/jquery/jquery-migrate.min.js\"></script>\n";
echo "        <script src=\"lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\n";
echo "        <script src=\"lib/easing/easing.min.js\"></script>\n";
echo "        <script src=\"lib/superfish/hoverIntent.js\"></script>\n";
echo "        <script src=\"lib/superfish/superfish.min.js\"></script>\n";
echo "        <script src=\"lib/wow/wow.min.js\"></script>\n";
echo "        <script src=\"lib/venobox/venobox.min.js\"></script>\n";
echo "        <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\n";
echo "        <script type=\"text/javascript\" src='schedule.js' id='schedule.js'></script>\n";
echo "        <script defer type='text/javascript' src='javascript/lazysizes.min.js'\n";
echo "            id='siteground-optimizer-lazy-sizes-js-js'>\n";
echo "        </script>\n";
echo "        <script defer type='text/javascript' src='javascript/priorityMenu.min.js' id='priority-menu-js'></script>\n";
echo "        <script type='text/javascript' src='javascript/wp-embed.min.js' id='wp-embed-js'>\n";
echo "        </script>\n";
echo "        <script type='text/javascript' src='javascript/countdown.js' id='countdown.js'></script>\n";
echo "        <script type='text/javascript' src='javascript/init.js' id='init.js'></script>\n";
echo "        <script>\n";
echo "            /(trident|msie)/i.test(navigator.userAgent) && document.getElementById && window.addEventListener &&\n";
echo "                window\n";
echo "                .addEventListener(\"hashchange\", function () {\n";
echo "                    var t,\n";
echo "                        e = location.hash.substring(1);\n";
echo "                    /^[A-z0-9_-]+$/.test(e) && (t = document.getElementById(e)) && (\n";
echo "                        /^(?:a|select|input|button|textarea)$/i.test(t.tagName) || (t.tabIndex = -1), t\n";
echo "                        .focus())\n";
echo "                }, !1);\n";
echo "        </script>\n";
echo "        \n";
echo "</body>\n";
echo "\n";
echo "</html>";
